### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by ozky** [mhogomchungu/qCheckGMail#30]
I try to build but get weird error everytime i try to build stable or git version with -DLXQTSUPPORT=true.
I'll post log file it's too long to here.
[qcheckgmail.txt](https://github.com/mhogomchungu/qCheckGMail/files/282245/qcheckgmail.txt)

**Comment by mhogomchungu** [comment]
There API must have changed in newer versions,will look into it.

**Comment by mhogomchungu** [comment]
Can you pull new sources from git and try to build again?

I think i have found and fixed the issue.

**Comment by ozky** [comment]
It fails still with same errors.

**Comment by mhogomchungu** [comment]
I was getting the same error you are getting and now i dont

what distribution are you using?
```
[mtz@ink qCheckGMail]$ cmake -DLXQTSUPPORT=true -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr ../projects/qCheckGMail/
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- found gcrypt header file: /usr/include/gcrypt.h
-- found gcrypt library: /usr/lib64/libgcrypt.so
-- Checking for module 'libsecret-1'
--   Found libsecret-1, version 0.18.4
-- 
--------------------------------------------------------------------------
-- kwallet support NOT found,will not build kwallet functionality
-- -----------------------------------------------------------------------
-- 
--------------------------------------------------------------------------
-- libsecret support found,will build libsecret functionality
-- -----------------------------------------------------------------------
-- Checking for module 'lxqt-qt5'
--   No package 'lxqt-qt5' found
-- Checking for module 'lxqt'
--   Found lxqt, version 0.10.0
-- 
------------------------------------------------------------------------------------------
-- lxqt support found,will build lxqt panel plugin based application
-- ------------------------------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mtz/qCheckGMail
[mtz@ink qCheckGMail]$ make
Scanning dependencies of target secretService
[  2%] Building C object lxqt_wallet/frontend/secret_service/CMakeFiles/secretService.dir/__/secret_service.c.o                                                                                     
[  4%] Linking C static library libsecretService.a
[  4%] Built target secretService
Scanning dependencies of target lxqtwallet-backend
[  6%] Building C object lxqt_wallet/backend/CMakeFiles/lxqtwallet-backend.dir/lxqtwallet.c.o
[  8%] Linking C static library liblxqtwallet-backend.a
[  8%] Built target lxqtwallet-backend
[ 10%] Generating moc_task.cpp
[ 12%] Generating ui_changepassworddialog.h
[ 14%] Generating ui_password_dialog.h
[ 17%] Generating moc_changepassworddialog.cpp
[ 19%] Generating moc_lxqt_internal_wallet.cpp
[ 21%] Generating moc_password_dialog.cpp
[ 23%] Generating moc_lxqt_secret_service.cpp
Scanning dependencies of target lxqtwallet
[ 25%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/changepassworddialog.cpp.o                                                                                                
[ 27%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/password_dialog.cpp.o
[ 29%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/lxqt_internal_wallet.cpp.o                                                                                                
[ 31%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/lxqt_wallet.cpp.o
[ 34%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/lxqt_secret_service.cpp.o                                                                                                 
[ 36%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/moc_changepassworddialog.cpp.o                                                                                            
[ 38%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/moc_lxqt_internal_wallet.cpp.o                                                                                            
[ 40%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/moc_password_dialog.cpp.o                                                                                                 
[ 42%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/moc_lxqt_secret_service.cpp.o                                                                                             
[ 44%] Building CXX object lxqt_wallet/frontend/CMakeFiles/lxqtwallet.dir/moc_task.cpp.o
[ 46%] Linking CXX static library liblxqtwallet.a
[ 46%] Built target lxqtwallet
[ 48%] Generating qrc_icon.cpp
[ 51%] Generating src/moc_qcheckgmail.cpp
[ 53%] Generating src/moc_walletmanager.cpp
[ 55%] Generating src/moc_addaccount.cpp
[ 57%] Generating src/moc_configurationoptionsdialog.cpp
[ 59%] Generating src/moc_statusicon.cpp
[ 61%] Generating src/moc_qcheckgmailplugin.cpp
[ 63%] Generating ui_walletmanager.h
[ 65%] Generating ui_addaccount.h
[ 68%] Generating ui_configurationoptionsdialog.h
Scanning dependencies of target qCheckGMail
[ 70%] Building CXX object CMakeFiles/qCheckGMail.dir/src/qcheckgmail.cpp.o
[ 72%] Building CXX object CMakeFiles/qCheckGMail.dir/src/accounts.cpp.o
[ 74%] Building CXX object CMakeFiles/qCheckGMail.dir/src/statusicon.cpp.o
[ 76%] Building CXX object CMakeFiles/qCheckGMail.dir/src/qcheckgmailplugin.cpp.o
[ 78%] Building CXX object CMakeFiles/qCheckGMail.dir/src/walletmanager.cpp.o
[ 80%] Building CXX object CMakeFiles/qCheckGMail.dir/src/addaccount.cpp.o
[ 82%] Building CXX object CMakeFiles/qCheckGMail.dir/src/configurationoptionsdialog.cpp.o
[ 85%] Building CXX object CMakeFiles/qCheckGMail.dir/src/moc_qcheckgmail.cpp.o
[ 87%] Building CXX object CMakeFiles/qCheckGMail.dir/src/moc_walletmanager.cpp.o
[ 89%] Building CXX object CMakeFiles/qCheckGMail.dir/src/moc_addaccount.cpp.o
[ 91%] Building CXX object CMakeFiles/qCheckGMail.dir/src/moc_configurationoptionsdialog.cpp.o
[ 93%] Building CXX object CMakeFiles/qCheckGMail.dir/src/moc_statusicon.cpp.o
[ 95%] Building CXX object CMakeFiles/qCheckGMail.dir/src/moc_qcheckgmailplugin.cpp.o
[ 97%] Building CXX object CMakeFiles/qCheckGMail.dir/qrc_icon.cpp.o
[100%] Linking CXX shared module libqCheckGMail.so
[100%] Built target qCheckGMail
[mtz@ink qCheckGMail]$ 

```

**Comment by ozky** [comment]
Yes i do it with clean build forlder and distro is Mageia 5.

**Comment by mhogomchungu** [comment]
I can reproduce the problem on ubuntu 16.04 but have so far failed to find a solution for it.

**Comment by ozky** [comment]
Good to know that i'm not alone with this problem,hope you will find soon fix to this.

**Comment by mhogomchungu** [comment]
It should be able to build now but it now fails to load with the following error: ``` "Plugin verification data mismatch in '/usr/lib64/lxqt-panel/libqCheckGMail.so'"```

Will appreciate if you test and see if the plugin loads successfully with you.

**Comment by ozky** [comment]
Now it builds without errors bug is fixed you can close this bug. :)

**Comment by mhogomchungu** [comment]
Did the plugin manage to load on your system?

It fails to load on my system for reasons i think specified here: http://doc.qt.io/qt-4.8/deployment-plugins.html#loading-and-verifying-plugins-dynamically

**Comment by ozky** [comment]
It's active on panel but not show any icon.

**Comment by mhogomchungu** [comment]
Does the icon still not show after you log out and log back in?

Downloading "mageia 5" right now to see why the icon does not show as the code looks fine.

**Comment by ozky** [comment]
No it won't show even logout and login.

**Comment by ozky** [comment]
Have you found some solution yet to fix this problem ?.

**Comment by mhogomchungu** [comment]
Not yet,i found out that mageia install image is 3.5GB big!!!

To put that figure into perspective,I am somewhere in Africa and my normal internet experience is limited to about 300MB a week.

For such large downloads,i usually go with overnight bundles that gives 4GB for two nights between 11 pm and 5 am but i doubt i will be able to pull down 3.5GB in one night and without dropping the connection.

All in all,mageia installation image is just too big for me to download at the moment.

Can you not use the Qt version? It should work just fine.

**Comment by ozky** [comment]
Yes i uderstand your network problem i can use qt version..... Don't download dvd iso it not include lxqt so you waste your time and network.

**Comment by ozky** [comment]
I have new information to you about that lxqt panel applet,i decided to start panel from icewm and get this from terminal.
`LC_ALL=C lxqt-panel
XdgDesktopFile "/usr/share/applications/lxqt-config.desktop" is not applicable
"Section \"volume2\" not found in /home/ozky/.config/lxqt/panel.conf."
"Section \"sensors2\" not found in /home/ozky/.config/lxqt/panel.conf."
WinIdChange 1200006 handle QWidgetWindow(0x10255f0, name="LXQtPanel panel1Window") QScreen(0xe89290, name="eDP1")
Systray started
"Plugin verification data mismatch in '/usr/lib64/lxqt-panel/libqCheckGMail.so'"
`

**Comment by mhogomchungu** [comment]
I am stuck on the "Plugin verification data mismatch" error on my PCLinuxOS main system and ubuntu 16.04 test machine.

It seems like the only way to overcome this error is to build the plugin with the same version of both compiler and Qt that were used to build LXQt.

This suggests that having an independent LXQt plugin that is build independently of LXQt is not a good idea.
